print("Welcome to the CO652 Knwoledge based systems collaborative project expert system") 
print(". . . ")
print(". . . . . . ")
print(". . . . . . . . . ")
print(". . . . . . . . . . . . . . . . . .")
print(". . . . . . . . . . . . . . . . . . . . . . .")
print(". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ")
print("What type of technical issue are you facing with to start with ?")
print("1. Blue Screen of Death (BSOD)\n2. Crashes or Freezing\n3. Display Errors\n4. Slow PC/Performance Issues\n5. Network Issues\n6. Other")
choice = int(input("Enter the number corresponding to your issue: "))